server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Esto es la clave para la SPA: si una ruta no existe, sirve el index.html
        # para que el JavaScript del frontend maneje el enrutamiento.
        try_files $uri $uri/ /index.html;
    }
}